# Generated by Django 4.1.3 on 2026-02-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_currency_provider_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="providers",
            field=models.ManyToManyField(related_name="blocks", to="app.provider"),
        ),
    ]
