# Generated by Django 4.1 on 2026-02-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_block_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='block_number',
            field=models.IntegerField(default=0),
        ),
    ]
